trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    $newSourceBranch = "v1.1.0" -replace 'refs/tags/', '' 
    $Command = "##vso[build.addbuildtag]"+$newSourceBranch 
    write-host "Create a Build TAG called $newSourceBranch" 
    write-host $Command
    git tag $newSourceBranch
    git push origin $newSourceBranch
  workingDirectory: $(Build.SourcesDirectory)
